[project]
name = "hacks"
version = "0.0.1"
description = "A hacks project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "lxml>=5.3.0",
    "natsort>=8.4.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
