versions:
  - name: Karpenter
    current:
      name: StaticSpider
      params:
        version: 1.0.8
    latest:
      name: GithubReleaseSpider
      params:
        owner: aws
        repository: karpenter-provider-aws
  - name: Jenkins
    current:
      name: StaticSpider
      params:
        version: 1.0.0
    latest:
      name: JenkinsStableSpider
      params: {}