versions:
  - name: Karpenter
    current:
      name: StaticSpider
      params:
        version: 1.0.8
    latest:
      name: GithubMixedReleaseSpider
      params:
        owner: aws
        repository: karpenter-provider-aws
        major: "1."
